/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatSVGIcon;
import java.awt.*;
import javax.swing.*;
import java.awt.geom.RoundRectangle2D;
import javax.swing.border.Border;
import model.Produk;
import model.Makanan;
import model.Minuman;
import controller.ProdukManager;

/**
 *
 * @author Faza Bilwildi Emyu_2311103083_SI-07-B
 */
public class DashboardForm extends javax.swing.JFrame {

    private CardLayout cardLayout;
    private ProdukManager produkManager;

    public DashboardForm() {
        initComponents();
        setLocationRelativeTo(null);
        produkManager = new ProdukManager();
        cardLayout = (CardLayout) mainPanel.getLayout();

        txtSearch.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Search here");

        Icon homeIcon_Focus = new FlatSVGIcon("assets/home-focus.svg", 24, 24);
        Icon historyIcon_Focus = new FlatSVGIcon("assets/history-focus.svg", 24, 24);
        Icon profileIcon_Focus = new FlatSVGIcon("assets/profile-focus.svg", 20, 20);
        Icon logOutIcon_Focus = new FlatSVGIcon("assets/log-focus.svg", 20, 20);

        Icon homeIcon = new FlatSVGIcon("assets/home-nonFocus.svg", 24, 24);
        Icon historyIcon = new FlatSVGIcon("assets/history-nonFocus.svg", 24, 24);
        Icon profileIcon = new FlatSVGIcon("assets/profile-nonFocus.svg", 20, 20);
        Icon logOutIcon = new FlatSVGIcon("assets/log-nonFocus.svg", 20, 20);

        addHoverEffect(btnHome, new Color(253, 82, 8), homeIcon, homeIcon_Focus);
        addHoverEffect(btnHistory, new Color(253, 82, 8), historyIcon, historyIcon_Focus);
        addHoverEffect(btnProfile, new Color(253, 82, 8), profileIcon, profileIcon_Focus);
        addHoverEffect(btnLogOut, new Color(253, 82, 8), logOutIcon, logOutIcon_Focus);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        foodCards = jPanel1 = new RoundedPanel(30, new Color(255, 255, 255)); 
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.BLACK, 2)); // Menambahkan border
        ;
        jLabel6 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtNama = new javax.swing.JLabel();
        txtHarga = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnAddProduk = new javax.swing.JButton();
        txtKetersediaan = new javax.swing.JLabel();
        sidePanel = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        homePanel = new javax.swing.JPanel();
        foodPanel = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        scrollFood = new javax.swing.JScrollPane();
        foodContent = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        orderPanel = new javax.swing.JPanel();
        btnCheckOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblOrder = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        historyPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        foodCards.setBackground(new java.awt.Color(255, 255, 255));
        foodCards.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        foodCards.setPreferredSize(new java.awt.Dimension(280, 170));
        foodCards.setLayout(new java.awt.BorderLayout(10, 0));

        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 100));
        foodCards.add(jLabel6, java.awt.BorderLayout.WEST);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));

        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtNama.setForeground(new java.awt.Color(51, 51, 51));
        txtNama.setText("Nama Produk");
        txtNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtNama);

        txtHarga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHarga.setForeground(new java.awt.Color(51, 51, 51));
        txtHarga.setText("Harga");
        txtHarga.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtHarga);

        txtDeskripsi.setForeground(new java.awt.Color(51, 51, 51));
        txtDeskripsi.setText("Deskripsi");
        txtDeskripsi.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel4.add(txtDeskripsi);

        foodCards.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(115, 23));
        jPanel5.setLayout(new java.awt.BorderLayout());

        btnAddProduk.setBackground(new java.awt.Color(253, 82, 8));
        btnAddProduk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduk.setText("Add");
        btnAddProduk.setPreferredSize(new java.awt.Dimension(115, 23));
        jPanel5.add(btnAddProduk, java.awt.BorderLayout.EAST);

        txtKetersediaan.setText("ketersediaan");
        jPanel5.add(txtKetersediaan, java.awt.BorderLayout.LINE_START);

        foodCards.add(jPanel5, java.awt.BorderLayout.SOUTH);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setPreferredSize(new java.awt.Dimension(200, 510));

        btnHome.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHome.setForeground(new java.awt.Color(51, 51, 51));
        btnHome.setText("Home");
        btnHome.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnHistory.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHistory.setForeground(new java.awt.Color(51, 51, 51));
        btnHistory.setText("History");
        btnHistory.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });

        btnLogOut.setBackground(new java.awt.Color(255, 255, 255));
        btnLogOut.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(51, 51, 51));
        btnLogOut.setText("Log Out");
        btnLogOut.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        btnProfile.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnProfile.setForeground(new java.awt.Color(51, 51, 51));
        btnProfile.setText("Profile");
        btnProfile.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(253, 82, 8));
        jPanel2.setPreferredSize(new java.awt.Dimension(3, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 249, Short.MAX_VALUE)
                .addComponent(btnLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        getContentPane().add(sidePanel, java.awt.BorderLayout.WEST);

        mainPanel.setBackground(new java.awt.Color(254, 254, 254));
        mainPanel.setPreferredSize(new java.awt.Dimension(900, 600));
        mainPanel.setLayout(new java.awt.CardLayout());

        homePanel.setBackground(new java.awt.Color(254, 254, 254));
        homePanel.setPreferredSize(new java.awt.Dimension(900, 600));
        homePanel.setLayout(new java.awt.BorderLayout());

        foodPanel.setBackground(new java.awt.Color(243, 243, 243));
        foodPanel.setPreferredSize(new java.awt.Dimension(600, 600));

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setForeground(new java.awt.Color(51, 51, 51));

        scrollFood.setBackground(new java.awt.Color(255, 255, 255));
        scrollFood.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        scrollFood.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        foodContent.setBackground(new java.awt.Color(243, 243, 243));
        foodContent.setForeground(new java.awt.Color(255, 255, 255));
        foodContent.setPreferredSize(new java.awt.Dimension(620, 2000));
        foodContent.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        scrollFood.setViewportView(foodContent);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout foodPanelLayout = new javax.swing.GroupLayout(foodPanel);
        foodPanel.setLayout(foodPanelLayout);
        foodPanelLayout.setHorizontalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(foodPanelLayout.createSequentialGroup()
                .addComponent(scrollFood, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150)
                .addComponent(jButton1)
                .addGap(99, 99, 99))
        );
        foodPanelLayout.setVerticalGroup(
            foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, foodPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(foodPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(foodPanelLayout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))
                    .addGroup(foodPanelLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(scrollFood, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        homePanel.add(foodPanel, java.awt.BorderLayout.WEST);

        orderPanel.setBackground(new java.awt.Color(255, 255, 255));
        orderPanel.setPreferredSize(new java.awt.Dimension(300, 600));

        btnCheckOut.setBackground(new java.awt.Color(253, 82, 8));
        btnCheckOut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCheckOut.setForeground(new java.awt.Color(255, 255, 255));
        btnCheckOut.setText("Check Out");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Total");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Sub Total");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Diskon");

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblTotal.setText("total");

        lblDiskon.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDiskon.setForeground(new java.awt.Color(51, 51, 51));
        lblDiskon.setText("diskon");

        lblSubTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(51, 51, 51));
        lblSubTotal.setText("sub total");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setMinimumSize(new java.awt.Dimension(300, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        TblOrder.setBackground(new java.awt.Color(255, 255, 255));
        TblOrder.setForeground(new java.awt.Color(51, 51, 51));
        TblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Jumlah", "Harga"
            }
        ));
        jScrollPane1.setViewportView(TblOrder);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("My Order");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel9))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSubTotal))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDiskon))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal))
                    .addComponent(btnCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblDiskon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotal))
                .addGap(18, 18, 18)
                .addComponent(btnCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        homePanel.add(orderPanel, java.awt.BorderLayout.CENTER);

        mainPanel.add(homePanel, "Home");

        historyPanel.setBackground(new java.awt.Color(243, 243, 243));
        historyPanel.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("History");

        jPanel1.setBackground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout historyPanelLayout = new javax.swing.GroupLayout(historyPanel);
        historyPanel.setLayout(historyPanelLayout);
        historyPanelLayout.setHorizontalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGroup(historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(historyPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(651, Short.MAX_VALUE))
        );
        historyPanelLayout.setVerticalGroup(
            historyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyPanelLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel2)
                .addGap(93, 93, 93)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        mainPanel.add(historyPanel, "History");

        profilePanel.setBackground(new java.awt.Color(243, 243, 243));
        profilePanel.setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Profile");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(694, Short.MAX_VALUE))
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(jLabel3)
                .addContainerGap(417, Short.MAX_VALUE))
        );

        mainPanel.add(profilePanel, "Profile");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);
        mainPanel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        cardLayout.show(mainPanel, "Home");
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        cardLayout.show(mainPanel, "History");
    }//GEN-LAST:event_btnHistoryActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        cardLayout.show(mainPanel, "Profile");
    }//GEN-LAST:event_btnProfileActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Tambahkan data dummy
        String nama = "Nasi Goreng";
        double harga = 15000.0;
        String deskripsi = "Nasi goreng lezat dengan tambahan ayam dan telur";
        boolean tersedia = true;
        String kategori = "Makanan";
//        String gambarPath = "path/to/image/nasi_goreng.jpg"; // Path gambar lokal

        Produk produk;
        if (kategori.equals("Makanan")) {
            produk = new Makanan(nama, harga, deskripsi, tersedia);
        } else {
            produk = new Minuman(nama, harga, deskripsi, tersedia);
        }

        produkManager.tambahProduk(produk); // Tambahkan ke model data

        createFoodCard(produk); // Tambahkan produk ke layout GUI

        JOptionPane.showMessageDialog(null, "Produk berhasil ditambahkan!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createFoodCard(Produk produk) {
        // Duplikasi panel foodCards (menggunakan template yang sudah ada)
        RoundedPanel foodCard = new RoundedPanel(30, new Color(255, 255, 255));  // Border radius 30px
        foodCard.setLayout(new java.awt.BorderLayout(10, 0));
        foodCard.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        foodCard.setPreferredSize(new java.awt.Dimension(280, 170));

        // Bagian gambar produk
        JLabel gambarLabel = new JLabel();
//        gambarLabel.setIcon(new ImageIcon(produk.getGambar())); // Gambar produk
        gambarLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        gambarLabel.setPreferredSize(new java.awt.Dimension(100, 100));
        foodCard.add(gambarLabel, java.awt.BorderLayout.WEST);

        // Panel untuk teks (nama, harga, deskripsi)
        JPanel panelText = new JPanel();
        panelText.setLayout(new javax.swing.BoxLayout(panelText, javax.swing.BoxLayout.Y_AXIS));
        panelText.setBackground(new java.awt.Color(255, 255, 255));

        // Nama produk
        JLabel txtNama = new JLabel(produk.getNama());
        txtNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // Font yang diinginkan
        txtNama.setForeground(new java.awt.Color(51, 51, 51));
        txtNama.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelText.add(txtNama);

        // Harga produk
        JLabel txtHarga = new JLabel("Rp " + produk.getHarga());
        txtHarga.setFont(new java.awt.Font("Segoe UI", 1, 12));
        txtHarga.setForeground(new java.awt.Color(51, 51, 51));
        txtHarga.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelText.add(txtHarga);

        // Deskripsi produk
        JLabel txtDeskripsi = new JLabel(produk.getDeskripsi());
        txtDeskripsi.setForeground(new java.awt.Color(51, 51, 51));
        txtDeskripsi.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        panelText.add(txtDeskripsi);

        // Tambahkan panel teks ke panel utama
        foodCard.add(panelText, java.awt.BorderLayout.CENTER);

        // Panel untuk ketersediaan dan tombol
        JPanel panelKetersediaan = new JPanel();
        panelKetersediaan.setBackground(new java.awt.Color(255, 255, 255));
        panelKetersediaan.setPreferredSize(new java.awt.Dimension(115, 23));
        panelKetersediaan.setLayout(new java.awt.BorderLayout());

        // Ketersediaan produk
        JLabel txtKetersediaan = new JLabel(produk.isTersedia() ? "Tersedia" : "Tidak Tersedia");
        panelKetersediaan.add(txtKetersediaan, java.awt.BorderLayout.LINE_START);

        // Tombol "Add" (opsional)
        JButton btnAddProduk = new JButton("Add");
        btnAddProduk.setBackground(new java.awt.Color(253, 82, 8));
        btnAddProduk.setFont(new java.awt.Font("Segoe UI", 1, 12));
        btnAddProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnAddProduk.setPreferredSize(new java.awt.Dimension(115, 23));
        panelKetersediaan.add(btnAddProduk, java.awt.BorderLayout.EAST);

        // Tambahkan hover effect
        btnAddProduk.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnAddProduk.setBackground(new Color(255, 255, 255));
                btnAddProduk.setForeground(new Color(253, 82, 8));
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnAddProduk.setBackground(new Color(253, 82, 8));
                btnAddProduk.setForeground(new Color(255, 255, 255));
            }
        });

        // Tambahkan panel ketersediaan ke panel utama
        foodCard.add(panelKetersediaan, java.awt.BorderLayout.SOUTH);

        // Tambahkan card ke panel foodCardsPanel
        foodContent.add(foodCard);

        // Refresh panel foodCardsPanel untuk menampilkan perubahan
        foodContent.revalidate();
        foodContent.repaint();
    }

    private void addHoverEffect(JButton button, Color focusTextColor, Icon defaultIcon, Icon focusedIcon) {
        /// Tambahkan listener untuk focus
        button.setIcon(defaultIcon);
        button.setIconTextGap(20);
        button.setHorizontalTextPosition(SwingConstants.RIGHT); // Teks di kanan ikon
        button.setHorizontalAlignment(SwingConstants.LEFT); // Ikon di kiri

        button.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent evt) {
                button.setForeground(focusTextColor); // Ubah warna teks
                button.setBackground(Color.WHITE);
                button.setIcon(focusedIcon); // Ubah ikon
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent evt) {
                button.setForeground(Color.BLACK); // Kembalikan ke warna teks default
                button.setIcon(defaultIcon); // Kembalikan ke ikon default
            }
        });
    }

    // Kelas RoundedPanel untuk memberikan border radius
    static class RoundedPanel extends JPanel {

        private Color backgroundColor;
        private int cornerRadius = 15;

        public RoundedPanel(int radius, Color bgColor) {
            super();
            cornerRadius = radius;
            backgroundColor = bgColor;
        }

        @Override
        protected void paintComponent(Graphics g) {
            super.paintComponent(g);
            Dimension arcs = new Dimension(cornerRadius, cornerRadius);
            int width = getWidth();
            int height = getHeight();
            Graphics2D graphics = (Graphics2D) g;
            graphics.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            // Menentukan warna background jika ada
            if (backgroundColor != null) {
                graphics.setColor(backgroundColor);
            } else {
                graphics.setColor(getBackground());
            }
            graphics.fillRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); // Gambar background
            graphics.setColor(new Color(200, 200, 200));
            graphics.drawRoundRect(0, 0, width - 1, height - 1, arcs.width, arcs.height); // Gambar border
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        UIManager.put("TextComponent.arc", 15);
        UIManager.put("Button.arc", 15);

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TblOrder;
    private javax.swing.JButton btnAddProduk;
    private javax.swing.JButton btnCheckOut;
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnProfile;
    private javax.swing.JPanel foodCards;
    private javax.swing.JPanel foodContent;
    private javax.swing.JPanel foodPanel;
    private javax.swing.JPanel historyPanel;
    private javax.swing.JPanel homePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JScrollPane scrollFood;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JLabel txtDeskripsi;
    private javax.swing.JLabel txtHarga;
    private javax.swing.JLabel txtKetersediaan;
    private javax.swing.JLabel txtNama;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
