/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms;

import databases.ProdukDB;
import java.awt.CardLayout;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.Makanan;
import model.Minuman;
import model.Produk;

/**
 *
 * @author M S I
 */
public class FrameTubes extends javax.swing.JFrame {

    /**
     * Creates new form FrameTubes
     */
    public FrameTubes() {
        initComponents();
        loadProduk();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnTambahProduk = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxTipe = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JTextField();
        cbxKetersediaan = new javax.swing.JComboBox<>();
        btnSimpanPerubahan = new javax.swing.JButton();
        btnHapusProduk = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduk = new javax.swing.JTable();
        btnLihatOrder = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        pnlTergantung = new javax.swing.JPanel();
        pnlPenyajian = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        txtPenyajian = new javax.swing.JComboBox<>();
        pnlKategori = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txtKategori = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        btnGambar = new javax.swing.JButton();
        txtGambar = new javax.swing.JLabel();
        lblId_produk = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnTambahProduk.setBackground(new java.awt.Color(0, 51, 255));
        btnTambahProduk.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnTambahProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnTambahProduk.setText("Tambah Produk");
        btnTambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahProdukActionPerformed(evt);
            }
        });

        txtNama.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("MENU ADMIN");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel7.setText("Tipe");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel8.setText("Nama Produk");

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel9.setText("Harga");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Ketersediaan");

        cbxTipe.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbxTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "makanan", "minuman" }));
        cbxTipe.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipeItemStateChanged(evt);
            }
        });
        cbxTipe.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbxTipePropertyChange(evt);
            }
        });

        txtHarga.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N

        cbxKetersediaan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        cbxKetersediaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tersedia", "tidak tersedia" }));

        btnSimpanPerubahan.setBackground(new java.awt.Color(0, 51, 255));
        btnSimpanPerubahan.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnSimpanPerubahan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpanPerubahan.setText("Simpan Perubahan");
        btnSimpanPerubahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPerubahanActionPerformed(evt);
            }
        });

        btnHapusProduk.setBackground(new java.awt.Color(0, 51, 255));
        btnHapusProduk.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnHapusProduk.setForeground(new java.awt.Color(255, 255, 255));
        btnHapusProduk.setText("Hapus Produk");
        btnHapusProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusProdukActionPerformed(evt);
            }
        });

        tblProduk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        tblProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No", "Nama Produk", "Deskripsi", "Harga", "Status Ketersediaan", "Tipe Produk", "Kategori", "Penyajian", "Gambar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdukMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduk);

        btnLihatOrder.setBackground(new java.awt.Color(0, 51, 255));
        btnLihatOrder.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        btnLihatOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnLihatOrder.setText("Lihat Order");
        btnLihatOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatOrderActionPerformed(evt);
            }
        });

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        pnlTergantung.setBackground(new java.awt.Color(255, 255, 255));
        pnlTergantung.setLayout(new java.awt.CardLayout());

        pnlPenyajian.setBackground(new java.awt.Color(255, 255, 255));
        pnlPenyajian.setPreferredSize(new java.awt.Dimension(297, 35));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel17.setText("Penyajian");

        txtPenyajian.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtPenyajian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "panas", "dingin" }));
        txtPenyajian.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtPenyajianItemStateChanged(evt);
            }
        });
        txtPenyajian.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPenyajianPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlPenyajianLayout = new javax.swing.GroupLayout(pnlPenyajian);
        pnlPenyajian.setLayout(pnlPenyajianLayout);
        pnlPenyajianLayout.setHorizontalGroup(
            pnlPenyajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPenyajianLayout.createSequentialGroup()
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(txtPenyajian, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlPenyajianLayout.setVerticalGroup(
            pnlPenyajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPenyajianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPenyajianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtPenyajian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlTergantung.add(pnlPenyajian, "cardPenyajian");

        pnlKategori.setBackground(new java.awt.Color(255, 255, 255));
        pnlKategori.setPreferredSize(new java.awt.Dimension(297, 35));

        jLabel18.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel18.setText("Kategori");

        txtKategori.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "pembuka", "utama", "penutup" }));
        txtKategori.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txtKategoriItemStateChanged(evt);
            }
        });
        txtKategori.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtKategoriPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout pnlKategoriLayout = new javax.swing.GroupLayout(pnlKategori);
        pnlKategori.setLayout(pnlKategoriLayout);
        pnlKategoriLayout.setHorizontalGroup(
            pnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriLayout.createSequentialGroup()
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlKategoriLayout.setVerticalGroup(
            pnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlKategoriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        pnlTergantung.add(pnlKategori, "cardKategori");

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel15.setText("Gambar");

        btnGambar.setText("Upload Gambar");
        btnGambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGambarActionPerformed(evt);
            }
        });

        txtGambar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        txtGambar.setText("Path");

        lblId_produk.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        lblId_produk.setText("ID Produk");

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel11.setText("Deskripsi");

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setRows(5);
        jScrollPane2.setViewportView(txtDeskripsi);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId_produk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(195, 195, 195)
                        .addComponent(btnLihatOrder))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pnlTergantung, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtNama)
                                                .addComponent(txtHarga)
                                                .addComponent(cbxKetersediaan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(btnTambahProduk)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(btnGambar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(btnSimpanPerubahan)
                                        .addGap(95, 95, 95)
                                        .addComponent(btnHapusProduk))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11)))))
                            .addComponent(btnLogOut)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnLihatOrder)))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblId_produk)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxTipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(cbxKetersediaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTergantung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(btnGambar)
                    .addComponent(txtGambar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahProduk)
                    .addComponent(btnSimpanPerubahan)
                    .addComponent(btnHapusProduk))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogOut)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahProdukActionPerformed
        // Mengambil input dari form
        String nama = txtNama.getText();
        String deskripsi = txtDeskripsi.getText();
        String hargaText = txtHarga.getText();
        String kategori = txtKategori.getSelectedItem().toString();
        String penyajian = txtPenyajian.getSelectedItem().toString();
        String gambar = txtGambar.getText();
        String tipe = cbxTipe.getSelectedItem().toString(); // Pilihan: "Makanan" atau "Minuman"
        boolean tersedia = cbxKetersediaan.getSelectedItem().toString().equalsIgnoreCase("Tersedia");

        // Validasi input
        if (hargaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom harga perlu diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double harga = Double.parseDouble(hargaText); // Konversi harga ke double

            ProdukDB produkDB = new ProdukDB();

            if (tipe.equalsIgnoreCase("makanan")) {
                // Buat objek Makanan
                Makanan makanan = new Makanan(nama, harga, deskripsi, tersedia, kategori);
                makanan.setGambar(gambar);

                // Tambahkan ke database
                produkDB.tambahProduk(makanan);

            } else {
                // Buat objek Minuman
                Minuman minuman = new Minuman(nama, harga, deskripsi, tersedia, penyajian);
                minuman.setGambar(gambar);

                // Tambahkan ke database
                produkDB.tambahProduk(minuman);
            }

            // Berikan feedback kepada pengguna
            JOptionPane.showMessageDialog(this, "Produk berhasil ditambahkan!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Refresh tampilan produk (misalnya, reload data di tabel atau panel)
            loadProduk();

            // Kosongkan form
            txtNama.setText("");
            txtDeskripsi.setText("");
            txtHarga.setText("");
            txtGambar.setText("");
            txtKategori.setSelectedIndex(0);
            txtPenyajian.setSelectedIndex(0);
            cbxTipe.setSelectedIndex(0);
            cbxKetersediaan.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahProdukActionPerformed

    private void loadProduk() {
        // Membuat koneksi ke database
        ProdukDB produkDB = new ProdukDB();

        // Mengambil semua produk dari database
        List<Produk> produkList = produkDB.semuaProduk();

        // Menyiapkan data untuk mengisi JTable
        DefaultTableModel model = (DefaultTableModel) tblProduk.getModel();
        model.setRowCount(0); // Menghapus data lama di tabel

        List<Makanan> makananList = new ArrayList<>();
        List<Minuman> minumanList = new ArrayList<>();
        for (Produk produk : produkList) {
            if (produk instanceof Makanan) {
                makananList.add((Makanan) produk);
            } else if (produk instanceof Minuman) {
                minumanList.add((Minuman) produk);
            }
        }
        // Gunakan makananList dan minumanList sesuai kebutuhan
        for (Makanan makanan : makananList) {
            Object[] row = new Object[9]; // Sesuaikan dengan jumlah kolom di tabel
            row[0] = makanan.getIdProduk();
            row[1] = makanan.getNamaMakanan(); // Asumsikan produk memiliki nama
            row[2] = makanan.getDeskripsi();
            row[3] = makanan.getHarga();
            row[4] = makanan.isTersedia() ? "Tersedia" : "Tidak Tersedia";
            row[5] = "makanan";
            row[6] = makanan.getKategoriMakanan();
            row[7] = "";
            row[8] = makanan.getGambar();

            // Menambahkan baris ke tabel
            model.addRow(row);
        }
        for (Minuman minuman : minumanList) {
            Object[] row = new Object[9]; // Sesuaikan dengan jumlah kolom di tabel
            row[0] = minuman.getIdProduk();
            row[1] = minuman.getNamaMinuman(); // Asumsikan produk memiliki nama
            row[2] = minuman.getDeskripsi();
            row[3] = minuman.getHarga();
            row[4] = minuman.isTersedia() ? "Tersedia" : "Tidak Tersedia";
            row[5] = "minuman";
            row[6] = "";
            row[7] = minuman.getPenyajian();
            row[8] = minuman.getGambar();

            // Menambahkan baris ke tabel
            model.addRow(row);
        }
    }

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnSimpanPerubahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPerubahanActionPerformed
        // Mengambil input dari form
        int idProduk = Integer.parseInt(lblId_produk.getText());
        String nama = txtNama.getText();
        String deskripsi = txtDeskripsi.getText();
        String hargaText = txtHarga.getText();
        String kategori = txtKategori.getSelectedItem().toString();
        String penyajian = txtPenyajian.getSelectedItem().toString();
        String gambar = txtGambar.getText();
        String tipe = cbxTipe.getSelectedItem().toString(); // Pilihan: "Makanan" atau "Minuman"
        boolean tersedia = cbxKetersediaan.getSelectedItem().toString().equalsIgnoreCase("Tersedia");

        // Validasi input
        if (hargaText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kolom harga perlu diisi", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double harga = Double.parseDouble(hargaText); // Konversi harga ke double

            ProdukDB produkDB = new ProdukDB();

            if (tipe.equalsIgnoreCase("makanan")) {
                // Buat objek Makanan
                Makanan makanan = new Makanan(nama, harga, deskripsi, tersedia, kategori);
                makanan.setGambar(gambar);

                // Tambahkan ke database
                produkDB.updateProduk(makanan, idProduk);

            } else {
                // Buat objek Minuman
                Minuman minuman = new Minuman(nama, harga, deskripsi, tersedia, penyajian);
                minuman.setGambar(gambar);

                // Tambahkan ke database
                produkDB.updateProduk(minuman, idProduk);
            }

            // Berikan feedback kepada pengguna
            JOptionPane.showMessageDialog(this, "Produk berhasil diUpdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);

            // Refresh tampilan produk (misalnya, reload data di tabel atau panel)
            loadProduk();

            // Kosongkan form
            txtNama.setText("");
            txtDeskripsi.setText("");
            txtHarga.setText("");
            txtGambar.setText("");
            txtKategori.setSelectedIndex(0);
            txtPenyajian.setSelectedIndex(0);
            cbxTipe.setSelectedIndex(0);
            cbxKetersediaan.setSelectedIndex(0);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka!", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanPerubahanActionPerformed

    private void btnHapusProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusProdukActionPerformed
        int id = Integer.parseInt(lblId_produk.getText());
        ProdukDB produkDB = new ProdukDB();
        produkDB.hapusProdukById(id);
        loadProduk();
    }//GEN-LAST:event_btnHapusProdukActionPerformed

    private void btnLihatOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatOrderActionPerformed
        new FrameOrder().setVisible(true);
    }//GEN-LAST:event_btnLihatOrderActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        new LoginForm().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void tblProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdukMouseClicked
        int row = tblProduk.getSelectedRow();

        if (row != -1) {
            // Ambil data dari row yang dipilih
            String idProduk = tblProduk.getValueAt(row, 0).toString(); // ID Produk
            String nama = tblProduk.getValueAt(row, 1).toString(); // Nama Produk
            String deskripsi = tblProduk.getValueAt(row, 2).toString(); // Deskripsi
            String harga = tblProduk.getValueAt(row, 3).toString(); // Harga
            String tersedia = tblProduk.getValueAt(row, 4).toString(); // Status Tersedia

            // Mengisi nilai ke form
            lblId_produk.setText(idProduk);
            txtNama.setText(nama);
            txtDeskripsi.setText(deskripsi);
            txtHarga.setText(harga);

            // Jika tipe produk adalah Makanan atau Minuman, tentukan kategori atau penyajian
            String tipeProduk = tblProduk.getValueAt(row, 5).toString();
            cbxTipe.setSelectedItem(tipeProduk);
            if (tipeProduk.equalsIgnoreCase("makanan")) {
                // Misalkan kategori disimpan pada kolom lain jika ada
                String kategori = tblProduk.getValueAt(row, 6).toString(); // Ambil kategori
                txtKategori.setSelectedItem(kategori);
            } else {
                // Misalkan penyajian disimpan pada kolom lain jika ada
                String penyajian = tblProduk.getValueAt(row, 7).toString(); // Ambil penyajian
                txtPenyajian.setSelectedItem(penyajian);
            }

            // Jika tersedia "Tersedia", set checkbox ke true
            cbxKetersediaan.setSelectedItem(tersedia.equalsIgnoreCase("tersedia"));

            // Untuk gambar, misalnya ditampilkan di txtGambar
            String gambar = tblProduk.getValueAt(row, 8).toString(); // Ambil gambar
            txtGambar.setText(gambar);

        }
    }//GEN-LAST:event_tblProdukMouseClicked

    private void cbxTipeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipeItemStateChanged
        String tipe = cbxTipe.getSelectedItem().toString();

        // CardLayout untuk pnlTergantung
        CardLayout cardLayout = (CardLayout) pnlTergantung.getLayout();

        if (tipe.equalsIgnoreCase("makanan")) {
            // Menampilkan cardKategori jika tipe yang dipilih adalah Makanan
            cardLayout.show(pnlTergantung, "cardKategori");
        } else {
            // Menampilkan cardPenyajian jika tipe yang dipilih adalah Minuman
            cardLayout.show(pnlTergantung, "cardPenyajian");
        }
    }//GEN-LAST:event_cbxTipeItemStateChanged

    private void cbxTipePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbxTipePropertyChange
        String tipe = cbxTipe.getSelectedItem().toString();

        // CardLayout untuk pnlTergantung
        CardLayout cardLayout = (CardLayout) pnlTergantung.getLayout();

        if (tipe.equalsIgnoreCase("makanan")) {
            // Menampilkan cardKategori jika tipe yang dipilih adalah Makanan
            cardLayout.show(pnlTergantung, "cardKategori");
        } else {
            // Menampilkan cardPenyajian jika tipe yang dipilih adalah Minuman
            cardLayout.show(pnlTergantung, "cardPenyajian");
        }
    }//GEN-LAST:event_cbxTipePropertyChange

    private void txtKategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtKategoriItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriItemStateChanged

    private void txtKategoriPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtKategoriPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriPropertyChange

    private void txtPenyajianItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txtPenyajianItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenyajianItemStateChanged

    private void txtPenyajianPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPenyajianPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPenyajianPropertyChange

    private void btnGambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGambarActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.IMAGE", "jpg", "gif", "png");
        fileChooser.addChoosableFileFilter(filter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            txtGambar.setText(path);
        }
    }//GEN-LAST:event_btnGambarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTubes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTubes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGambar;
    private javax.swing.JButton btnHapusProduk;
    private javax.swing.JButton btnLihatOrder;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnSimpanPerubahan;
    private javax.swing.JButton btnTambahProduk;
    private javax.swing.JComboBox<String> cbxKetersediaan;
    private javax.swing.JComboBox<String> cbxTipe;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblId_produk;
    private javax.swing.JPanel pnlKategori;
    private javax.swing.JPanel pnlPenyajian;
    private javax.swing.JPanel pnlTergantung;
    private javax.swing.JTable tblProduk;
    private javax.swing.JTextArea txtDeskripsi;
    private javax.swing.JLabel txtGambar;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JComboBox<String> txtKategori;
    private javax.swing.JTextField txtNama;
    private javax.swing.JComboBox<String> txtPenyajian;
    // End of variables declaration//GEN-END:variables
}
